<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ur_10_robot">

<!--
  Author: Kelsey Hawkins
  Contributers: Jimmy Da Silva, Ajit Krisshna N L, Muhammad Asif Rana
-->

  <xacro:macro name="cylinder_inertial_right" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="ur10_robot_right" params="prefix joint_limited
    shoulder_pan_lower_limit:=${-pi}    shoulder_pan_upper_limit:=${pi}
    shoulder_lift_lower_limit:=${-pi}    shoulder_lift_upper_limit:=${pi}
    elbow_joint_lower_limit:=${-pi}    elbow_joint_upper_limit:=${pi}
    wrist_1_lower_limit:=${-pi}    wrist_1_upper_limit:=${pi}
    wrist_2_lower_limit:=${-pi}    wrist_2_upper_limit:=${pi}
    wrist_3_lower_limit:=${-pi}    wrist_3_upper_limit:=${pi}
    transmission_hw_interface:=hardware_interface/PositionJointInterface">

    <!-- Inertia parameters -->
    <xacro:property name="base_mass_right" value="4.0" />  <!-- This mass might be incorrect -->
    <xacro:property name="shoulder_mass_right" value="7.778" />
    <xacro:property name="upper_arm_mass_right" value="12.93" />
    <xacro:property name="forearm_mass_right" value="3.87" />
    <xacro:property name="wrist_1_mass_right" value="1.96" />
    <xacro:property name="wrist_2_mass_right" value="1.96" />
    <xacro:property name="wrist_3_mass_right" value="0.202" />

    <!-- These parameters are borrowed from the urcontrol.conf file
        but are not verified for the correct permutation.
        The permutation was guessed by looking at the UR5 parameters.
        Serious use of these parameters needs further inspection. -->
    <xacro:property name="shoulder_cog_right" value="0.00008 0.00244 -0.037" />
    <xacro:property name="upper_arm_cog_right" value="0.00001 0.15061 0.38757" />
    <xacro:property name="forearm_cog_right" value="-0.00012 0.06112 0.1984" />
    <xacro:property name="wrist_1_cog_right" value="-0.00021 -0.00112 0.02269" />
    <xacro:property name="wrist_2_cog_right" value="-0.00021 0.00112 0.002269" />
    <xacro:property name="wrist_3_cog_right" value="0 -0.001156 -0.00149" />

    <!-- Kinematic model -->
    <!-- Properties from urcontrol.conf -->
    <xacro:property name="d1_right" value="0.1273" />
    <xacro:property name="a2_right" value="-0.612" />
    <xacro:property name="a3_right" value="-0.5723" />
    <xacro:property name="d4_right" value="0.163941" />
    <xacro:property name="d5_right" value="0.1157" />
    <xacro:property name="d6_right" value="0.0922" />

    <!-- Arbitrary offsets for shoulder/elbow joints -->
    <xacro:property name="shoulder_offset_right" value="0.220941" />  <!-- measured from model -->
    <xacro:property name="elbow_offset_right" value="-0.1719" /> <!-- measured from model -->

    <!-- link lengths used in model -->
    <xacro:property name="shoulder_height_right" value="${d1_right}" />
    <xacro:property name="upper_arm_length_right" value="${-a2_right}" />
    <xacro:property name="forearm_length_right" value="${-a3_right}" />
    <xacro:property name="wrist_1_length_right" value="${d4_right - elbow_offset_right - shoulder_offset_right}" />
    <xacro:property name="wrist_2_length_right" value="${d5_right}" />
    <xacro:property name="wrist_3_length_right" value="${d6_right}" />

    <link name="${prefix}base_link_right" >
      <visual>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/base.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="0.038" mass="${base_mass_right}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}shoulder_pan_joint_right" type="revolute">
      <parent link="${prefix}base_link_right" />
      <child link = "${prefix}shoulder_link_right" />
      <origin xyz="0.0 0.0 ${shoulder_height_right}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}shoulder_link_right">
      <visual>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="0.178" mass="${shoulder_mass_right}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}shoulder_lift_joint_right" type="revolute">
      <parent link="${prefix}shoulder_link_right" />
      <child link = "${prefix}upper_arm_link_right" />
      <!-- <origin xyz="0.0 ${shoulder_offset_right} 0.0" rpy="0.0 ${pi / 2.0} 0.0" /> -->
      <origin xyz="0.0 ${shoulder_offset_right} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link_right">
      <visual>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="${-a2_right}" mass="${upper_arm_mass_right}">
        <origin xyz="0.0 0.0 ${-a2_right/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}elbow_joint_right" type="revolute">
      <parent link="${prefix}upper_arm_link_right" />
      <child link = "${prefix}forearm_link_right" />
      <origin xyz="0.0 ${elbow_offset_right} ${upper_arm_length_right}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link_right">
      <visual>
         <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="${-a3_right}" mass="${forearm_mass_right}">
        <origin xyz="0.0 0.0 ${-a3_right/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}wrist_1_joint_right" type="revolute">
      <parent link="${prefix}forearm_link_right" />
      <child link = "${prefix}wrist_1_link_right" />
      <!-- <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" /> -->
      <origin xyz="0.0 0.0 ${forearm_length_right}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link_right">
      <visual>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="0.12" mass="${wrist_1_mass_right}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}wrist_2_joint_right" type="revolute">
      <parent link="${prefix}wrist_1_link_right" />
      <child link = "${prefix}wrist_2_link_right" />
      <origin xyz="0.0 ${wrist_1_length_right} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link_right">
      <visual>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="0.12" mass="${wrist_2_mass_right}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}wrist_3_joint_right" type="revolute">
      <parent link="${prefix}wrist_2_link_right" />
      <child link = "${prefix}wrist_3_link_right" />
      <origin xyz="0.0 0.0 ${wrist_2_length_right}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link_right">
      <visual>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://arm_controller/ur_description/meshes/ur10/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial_right radius="0.075" length="0.12" mass="${wrist_3_mass_right}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial_right>
    </link>

    <joint name="${prefix}ee_fixed_joint_right" type="fixed">
      <parent link="${prefix}wrist_3_link_right" />
      <child link = "${prefix}ee_link_right" />
      <origin xyz="0.0 ${wrist_3_length_right} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${prefix}ee_link_right">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>

    <xacro:ur_arm_transmission_right prefix="${prefix}" hw_interface="${transmission_hw_interface}" />
    <xacro:ur_arm_gazebo_right prefix="${prefix}" />

    <!-- ROS base_link_right to UR 'Base' Coordinates transform -->
    <link name="${prefix}base_right"/>
    <joint name="${prefix}base_link_right-base_fixed_joint_right" type="fixed">
      <!-- NOTE: this rotation is only needed as long as base_link_right itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
      <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
      <parent link="${prefix}base_link_right"/>
      <child link="${prefix}base_right"/>
    </joint>

    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="${prefix}tool0_right"/>
    <joint name="${prefix}wrist_3_link_right-tool0_fixed_joint_right" type="fixed">
      <origin xyz="0 ${wrist_3_length_right} 0" rpy="${pi/-2.0} 0 0"/>
      <parent link="${prefix}wrist_3_link_right"/>
      <child link="${prefix}tool0_right"/>
    </joint>

  </xacro:macro>


  <xacro:macro name="ur_arm_transmission_right" params="prefix hw_interface">

    <transmission name="${prefix}shoulder_pan_trans_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}shoulder_pan_joint_right">
        <hardwareInterface>${hw_interface}</hardwareInterface>
      </joint>
      <actuator name="${prefix}shoulder_pan_motor_right">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="${prefix}shoulder_lift_trans_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}shoulder_lift_joint_right">
        <hardwareInterface>${hw_interface}</hardwareInterface>
      </joint>
      <actuator name="${prefix}shoulder_lift_motor_right">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="${prefix}elbow_trans_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}elbow_joint_right">
        <hardwareInterface>${hw_interface}</hardwareInterface>
      </joint>
      <actuator name="${prefix}elbow_motor_right">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="${prefix}wrist_1_trans_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}wrist_1_joint_right">
        <hardwareInterface>${hw_interface}</hardwareInterface>
      </joint>
      <actuator name="${prefix}wrist_1_motor_right">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="${prefix}wrist_2_trans_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}wrist_2_joint_right">
        <hardwareInterface>${hw_interface}</hardwareInterface>
      </joint>
      <actuator name="${prefix}wrist_2_motor_right">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="${prefix}wrist_3_trans_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}wrist_3_joint_right">
        <hardwareInterface>${hw_interface}</hardwareInterface>
      </joint>
      <actuator name="${prefix}wrist_3_motor_right">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

  <xacro:macro name="ur_arm_gazebo_right" params="prefix">

    <gazebo reference="${prefix}shoulder_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}upper_arm_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}forearm_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}wrist_1_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}wrist_3_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}wrist_2_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}ee_link_right">
      <selfCollide>true</selfCollide>
    </gazebo>

  </xacro:macro>


</robot>
